apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-cicd-app
  labels:
    app: react-cicd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-cicd-app
  template:
    metadata:
      labels:
        app: react-cicd-app
    spec:
      containers:
        - name: react-cicd-app
          image: vinyassk/react-cicd-app:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
