apiVersion: v1
kind: Service
metadata:
  name: react-cicd-service
  labels:
    app: react-cicd-app
spec:
  type: NodePort
  selector:
    app: react-cicd-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
